server:
  port: 80
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enable: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-2.ce6cbg1kwcyt.ap-northeast-2.rds.amazonaws.com:3306/cs101?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: ha119302

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
      format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect




  logging:
    level:
      org.hibernate.SQL: debug

salt: "tkddnrkaksemsthfxm"